# docker-compose.yml
version: '3'

services:
  waline:
    container_name: waline
    image: lizheming/waline:latest
    restart: always
    ports:
      - 80:8360
    volumes:
      - /__temp/waline/data:/app/data
    environment:
      TZ: 'Asia/Shanghai'
      SQLITE_PATH: '/app/data'
      JWT_TOKEN: 'waline'
      SITE_NAME: 'waline'
      SITE_URL: 'http://localhost'
      SECURE_DOMAINS: '0.0.0.0'
      AUTHOR_EMAIL: 'luansaibiao@163.com'
